name: common-attack-knowledge-base-enhancer
services:
  database:
    image: postgres
    restart: unless-stopped
    container_name: 'knowledge-base'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_SECRET}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql